version: "3.7"
services:
  web:
    image: nginx:latest
    container_name: web-container
    ports:
      - "80:80"
    labels:
      qiita.comefigo.service: "web"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/log:/var/log/nginx
    depends_on:
      - app
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: app
    container_name: app-container
    labels:
      qiita.comefigo.service: "app"
    depends_on:
      - db
  db:
    image: redis:4
    container_name: db-container
    labels:
      qiita.comefigo.service: "db"
